
-- Tracker:AddLayouts("layouts/broadcast.json")
-- Tracker:AddLayouts("layouts/settings/settings_popup.json")
-- Tracker:AddLayouts("layouts/settings/tracker_slot_data.json")
-- Tracker:AddLayouts("layouts/settings/tracker_settings.json")

Tracker:AddLayouts("layouts/seeds.json")
Tracker:AddLayouts("layouts/item_grids.json")
Tracker:AddLayouts("layouts/tool_grid.json")
Tracker:AddLayouts("layouts/misc.json")
Tracker:AddLayouts("layouts/island_grid.json")
Tracker:AddLayouts("layouts/settings.json")
Tracker:AddLayouts("layouts/powers.json")
Tracker:AddLayouts("layouts/bachelors.json")
Tracker:AddLayouts("layouts/bachelorettes.json")
Tracker:AddLayouts("layouts/villagers.json")
Tracker:AddLayouts("layouts/tracker.json")
Tracker:AddLayouts("layouts/tabs/tabs_no_booksanity.json")
Tracker:AddLocations("locations/Cooksanity_friends.json")
Tracker:AddLocations("locations/Cropsanity_friends.json")
Tracker:AddLocations("locations/Craft1_friends.json")
Tracker:AddLocations("locations/Craft2_friends.json")